### ISSUE TITLE
The process withdraws worker stops processing transactions if one fails

### ISSUE THREAD

**Issue by morion4000** [morion4000/telegram-tip-bot#8]
https://github.com/morion4000/telegram-tip-bot/blob/master/workers/process_withdraws.js

**Comment by morion4000** [comment]
Implement a try/catch and send an email that a transaction is failing to process.

**Comment by morion4000** [comment]
Withdrawal transactions fail for addresses like: `WEBD$gA@GX6Ep9nNWKfZKQALxqKePa3V2zjTTA$$`

**Comment by morion4000** [comment]
Cloudwatch logs:

> 2021-02-19T12:56:05.320Z 71c36287-9469-41c6-b702-ba653f6b51d7 ERROR Invoke Error {"errorType":"Error","errorMessage":"Need at least one of 'text' or 'html' parameters specified","statusCode":400,"stack":["Error: Need at least one of 'text' or 'html' parameters specified"," at IncomingMessage.<anonymous> (/var/task/node_modules/mailgun-js/lib/request.js:327:17)"," at IncomingMessage.emit (events.js:326:22)"," at endReadableNT (_stream_readable.js:1241:12)"," at processTicksAndRejections (internal/process/task_queues.js:84:21)"]} 

> 2021-02-19T12:56:04.918Z 71c36287-9469-41c6-b702-ba653f6b51d7 ERROR error sending transaction { status: 200, statusText: 'OK', headers: { 'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'access-control-allow-credentials': 'true', 'content-type': 'application/json; charset=utf-8', 'content-length': '105', etag: 'W/"69-sATN9u/JoPkC/L4YyFrzgbrRiEY"', date: 'Fri, 19 Feb 2021 12:56:04 GMT', connection: 'close' }, config: { url: 'xxx/wallets/create-transaction/WEBD$gDnTKoDgfy4k8f3ahDfCGG7yKQMxgdrDBr$/WEBD%24gA%40GX6Ep9nNWkgZKQALxqKePa3V2zjTTA%24%24/530/9', method: 'get', headers: { Accept: 'application/json', 'User-Agent': 'axios/0.21.0' }, transformRequest: [ [Function: transformRequest] ], transformResponse: [ [Function: transformResponse] ], timeout: 0, adapter: [Function: httpAdapter], xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, maxBodyLength: -1, validateStatus: [Function: validateStatus], data: undefined }, request: ClientRequest { _events: [Object: null prototype] { socket: [Function], abort: [Function], aborted: [Function], connect: [Function], error: [Function], timeout: [Function], prefinish: [Function: requestOnPrefinish] }, _eventsCount: 7, _maxListeners: undefined, outputData: [], outputSize: 0, writable: true, _last: true, chunkedEncoding: false, shouldKeepAlive: false, _defaultKeepAlive: true, useChunkedEncodingByDefault: false, sendDate: false, _removedConnection: false, _removedContLen: false, _removedTE: false, _contentLength: 0, _hasBody: true, _trailer: '', finished: true, _headerSent: true, socket: Socket { connecting: false, _hadError: false, _parent: null, _host: 'tipbotnode.hostero.eu', _readableState: [ReadableState], readable: true, _events: [Object: null prototype], _eventsCount: 7, _maxListeners: undefined, _writableState: [WritableState], writable: false, allowHalfOpen: false, _sockname: null, _pendingData: null, _pendingEncoding: '', server: null, _server: null, parser: null, _httpMessage: [Circular], [Symbol(asyncId)]: 214, [Symbol(kHandle)]: [TCP], [Symbol(kSetNoDelay)]: false, [Symbol(lastWriteQueueSize)]: 0, [Symbol(timeout)]: null, [Symbol(kBuffer)]: null, [Symbol(kBufferCb)]: null, [Symbol(kBufferGen)]: null, [Symbol(kCapture)]: false, [Symbol(kBytesRead)]: 0, [Symbol(kBytesWritten)]: 0 }, connection: Socket { connecting: false, _hadError: false, _parent: null, _host: 'tipbotnode.hostero.eu', _readableState: [ReadableState], readable: true, _events: [Object: null prototype], _eventsCount: 7, _maxListeners: undefined, _writableState: [WritableState], writable: false, allowHalfOpen: false, _sockname: null, _pendingData: null, _pendingEncoding: '', server: null, _server: null, parser: null, _httpMessage: [Circular], [Symbol(asyncId)]: 214, [Symbol(kHandle)]: [TCP], [Symbol(kSetNoDelay)]: false, [Symbol(lastWriteQueueSize)]: 0, [Symbol(timeout)]: null, [Symbol(kBuffer)]: null, [Symbol(kBufferCb)]: null, [Symbol(kBufferGen)]: null, [Symbol(kCapture)]: false, [Symbol(kBytesRead)]: 0, [Symbol(kBytesWritten)]: 0 }, _header: 'GET /xxx/wallets/create-transaction/WEBD$gDnTKoDgfy4k8f3ahDfCGG7yKQMxgdrDBr$/WEBD%24gA%40GX6Ep9nNWkgZKQALxqKePa3V2zjTTA%24%24/530/9 HTTP/1.1\r\n' + 'Accept: application/json\r\n' + 'User-Agent: axios/0.21.0\r\n' + 'Host: tipbotnode.hostero.eu:9999\r\n' + 'Connection: close\r\n' + '\r\n', _keepAliveTimeout: 0, _onPendingData: [Function: noopPendingOutput], agent: Agent { _events: [Object: null prototype], _eventsCount: 2, _maxListeners: undefined, defaultPort: 80, protocol: 'http:', options: [Object], requests: {}, sockets: [Object], freeSockets: {}, keepAliveMsecs: 1000, keepAlive: false, maxSockets: Infinity, maxFreeSockets: 256, maxTotalSockets: Infinity, totalSocketCount: 1, scheduling: 'fifo', [Symbol(kCapture)]: false }, socketPath: undefined, method: 'GET', insecureHTTPParser: undefined, path: '/xxx/wallets/create-transaction/WEBD$gDnTKoDgfy4k8f3ahDfCGG7yKQMxgdrDBr$/WEBD%24gA%40GX6Ep9nNWkgZKQALxqKePa3V2zjTTA%24%24/530/9', _ended: true, res: IncomingMessage { _readableState: [ReadableState], readable: false, _events: [Object: null prototype], _eventsCount: 3, _maxListeners: undefined, socket: [Socket], connection: [Socket], httpVersionMajor: 1, httpVersionMinor: 1, httpVersion: '1.1', complete: true, headers: [Object], rawHeaders: [Array], trailers: {}, rawTrailers: [], aborted: false, upgrade: false, url: '', method: null, statusCode: 200, statusMessage: 'OK', client: [Socket], _consuming: false, _dumped: false, req: [Circular], responseUrl: 'http://xxx/wallets/create-transaction/WEBD$gDnTKoDgfy4k8f3ahDfCGG7yKQMxgdrDBr$/WEBD%24gA%40GX6Ep9nNWkgZKQALxqKePa3V2zjTTA%24%24/530/9', redirects: [], [Symbol(kCapture)]: false }, aborted: false, timeoutCb: null, upgradeOrConnect: false, parser: null, maxHeadersCount: null, reusedSocket: false, host: 'tipbotnode.hostero.eu', protocol: 'http:', _redirectable: Writable { _writableState: [WritableState], writable: true, _events: [Object: null prototype], _eventsCount: 2, _maxListeners: undefined, _options: [Object], _ended: true, _ending: true, _redirectCount: 0, _redirects: [], _requestBodyLength: 0, _requestBodyBuffers: [], _onNativeResponse: [Function], _currentRequest: [Circular], _currentUrl: 'xxx/wallets/create-transaction/WEBD$gDnTKoDgfy4k8f3ahDfCGG7yKQMxgdrDBr$/WEBD%24gA%40GX6Ep9nNWkgZKQALxqKePa3V2zjTTA%24%24/530/9', [Symbol(kCapture)]: false }, [Symbol(kCapture)]: false, [Symbol(kNeedDrain)]: false, [Symbol(corked)]: 0, [Symbol(kOutHeaders)]: [Object: null prototype] { accept: [Array], 'user-agent': [Array], host: [Array] } }, data: { result: false, message: 'Failed Signing the transaction', reason: 'To.Object Address is not specified' } }

**Comment by morion4000** [comment]
Sometimes users try to withdraw to the bot address (should not be allowed):

> { result: false, message: 'Failed Signing the transaction', reason: 'To.Object Address is included in the input and it should not be included in output ' }

**Comment by morion4000** [comment]
Fixed by https://github.com/morion4000/telegram-tip-bot/commit/cbd80dc056063a89a696fd8474db1d5cb104d6e1
